#!/bin/bash

# export FLASK_APP=app.py
# flask run --port 5001

py3=`python3 -c "import sys; print('1' if sys.version_info >= (3,0) else '0')"`
py=`python3 -c "import sys; print('1' if sys.version_info >= (3,0) else '0')"`


if [ "$1" = "flask" ]; then
    echo "-------------------------------------------"
    echo "| ShinchanJS/Flask"
    echo "-------------------------------------------"
    export FLASK_APP=app.py
    flask run --port 5001
elif [ ${py3} -eq 1 ]; then
    echo "-------------------------------------------"
    echo "| ShinchanJS/python3-HttpServer"
    echo "-------------------------------------------"
    # use python 3 default http server
    echo "*WARNING*"
    echo "This server only serves static content. Serverside features such as bootstrap edit will not work."
    echo "To run flask server, use: ./run flask"
    echo ""
    python -m http.server 5001
else
    echo "Python 3 is required"
fi
