#!/bin/bash

# export FLASK_APP=app.py
# flask run --port 5001

py3=`python3 -c "import sys; print('1' if sys.version_info >= (3,0) else '0')"`
py=`python3 -c "import sys; print('1' if sys.version_info >= (3,0) else '0')"`
if [ ${py3} -eq 1 ]; then
    python3 -m http.server 5001
elif [ ${py3} -eq 1 ]; then
    # use python 3 default http server
    python -m http.server 5001
else
    echo "Python 3 is required"
fi
